# Generated by Django 5.1 on 2024-08-21 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit_viewer', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_maquina', models.CharField(max_length=100)),
                ('tera_hash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temperatura', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bit_viewer.usuarioinfo')),
            ],
        ),
    ]
