# Generated by Django 5.1 on 2024-08-21 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit_viewer', '0005_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='pool',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bit_viewer.pool'),
        ),
    ]
