# Generated by Django 5.1.1 on 2024-09-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hashrate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temperatura', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pool', models.CharField(max_length=100)),
                ('id_maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.maquina')),
                ('id_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.pool')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.usuarioinfo')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoBinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('moeda', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=100)),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lucro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lucro_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_medio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_medio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_medio_total_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_medio_total_total_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_medio_total_total_total_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_medio_total_total_total_total_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_medio_total_total_total_total_total_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_medio_total_total_total_total_total_total_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_medio_total_total_total_total_total_total_total_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_medio_total_total_total_total_total_total_total_total_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.usuarioinfo')),
            ],
        ),
    ]
