# Generated by Django 5.1.1 on 2024-09-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_rename_temperatura_maquina_chip_temperature_max_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquina',
            old_name='pcb_temperatuer_max',
            new_name='pcb_temperature_max',
        ),
    ]
