# Generated by Django 5.1.1 on 2024-09-23 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_rename_pcb_temperatuer_max_maquina_pcb_temperature_max'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='id_usuario',
        ),
    ]
