# Generated by Django 5.1.1 on 2024-10-13 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_remove_maquina_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
